version: '3'

services:
  wppconnect-server:
    build: 
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn start
    networks: 
      - wpp-network
    tty: true

  nginx:
    build: 
      context: ./wppconnect-nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8081:8081" #wppconnect
    networks: 
      - wpp-network
    depends_on:
      - wppconnect-server

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge